<style>
    /* Modal */
    .modal-header {
        font-family: 'Times New Roman', Times, serif;
    }

    .modalsimpan {
        background-color: #0fa114;
        color: white;
    }

    .modalsimpan:hover {
        background-color: #fff2cc;
        color: black;
    }

    .modaltutup {
        background-color: #f44336;
        color: white;
    }

    .modaltutup:hover {
        background-color: #fff2cc;
        color: black;
    }

    /* End of Modal */

    .focus-in-contract {
        -webkit-animation: focus-in-contract 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: focus-in-contract 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2022-12-10 3:7:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation focus-in-contract
 * ----------------------------------------
 */
    @-webkit-keyframes focus-in-contract {
        0% {
            letter-spacing: 1em;
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }

        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }

    @keyframes focus-in-contract {
        0% {
            letter-spacing: 1em;
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }

        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
    @media screen and (max-width: 992px) {
        h1 {
            font-size: 35px;
        }
    }

    /* Header Beranda */

    body {
        height: 100vh;
    }

    .banner {
        background-image: url('../img/bannerindex.png');
        background-repeat: no-repeat;
        background-size: cover;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .statuspelanggan {
        text-align: center;
        width: fit-content;
        height: fit-content;
        padding-top: 5px;
        padding-bottom: 5px;
        padding-right: 10px;
        padding-left: 10px;
        border-radius: 10px;
    }

    /* End Of Header Beranda */


    /* Navbar */
    nav {
        font-family: 'Times New Roman', Times, serif;
        font-size: large;
        background-color: white;
    }

    .judul {
        font-size: larger;
        color: #444444;
    }

    .judul:hover {
        color: #7f6000;
    }

    .nav-link {
        color: #444444;
    }

    .nav-link:hover {
        color: #7f6000;
    }

    @media screen and (min-width: 992px) {
        .nav-link:hover {
            border-bottom: 1px solid #7f6000;
            margin-bottom: -1px;
        }
    }

    /* End Of Navbar */

    h3 {
        font-family: 'Times New Roman', Times, serif;
    }

    /* Kartu Pelanggan */

    .kp {
        background-color: white;
        color: black;
    }

    .kp:hover {
        background-color: black;
        color: white;
    }

    /* End Of Kartu Pelanggan */

    @media screen and (max-width: 992px) {
        .ubahpelanggan {
            margin-bottom: 2px;
        }

        .ubahtransaksi {
            margin-bottom: 2px;
        }

    }

    /* Halaman Petugas */
    .petugas {
        background-color: white;
        margin-top: 75px;
        border-radius: 6px;
        padding: 20px;
    }

    .tambahpetugas {
        margin-top: 7px;
        background-color: #0b5394;
        color: white;
    }

    .tambahpetugas:hover {
        background-color: #fff2cc;
        color: black;
    }

    .ubahpetugas {
        margin-top: 2px;
        background-color: #0b5394;
        color: white;
        width: 57px;
    }

    .ubahpetugas:hover {
        background-color: #fff2cc;
        color: black;
    }

    .hapuspetugas {
        margin-top: 2px;
        background-color: #f44336;
        color: white;
    }

    .hapuspetugas:hover {
        color: black;
        background-color: #fff2cc;
    }

    .hapuspetugas1 {
        margin-top: 2px;
    }

    .addfotopetugas {
        margin-top: 5px;
    }

    .bukafotopetugas {
        margin-top: 5px;
    }

    /* End Of Halaman Petugas */

    /* Halaman Pelanggan */
    .pelanggan {
        background-color: white;
        margin-top: 75px;
        border-radius: 6px;
        padding: 20px;
    }

    .tambahpelanggan {
        margin-top: 7px;
        background-color: #0b5394;
        color: white;
    }

    .tambahpelanggan:hover {
        background-color: #fff2cc;
        color: black;
    }

    .pdfpelanggan {
        margin-top: 7px;
        background-color: #0fa114;
        color: white;
    }

    .pdfpelanggan:hover {
        background-color: #fff2cc;
        color: black;
    }

    .xlspelanggan {
        margin-top: 7px;
        background-color: #0fa114;
        color: white;
    }

    .xlspelanggan:hover {
        background-color: #fff2cc;
        color: black;
    }

    .hapuspelanggan {
        background-color: #f44336;
        color: white;
    }

    .hapuspelanggan:hover {
        color: black;
        background-color: #fff2cc;
    }

    .ubahpelanggan {
        background-color: #0b5394;
        color: white;
        width: 57px;
    }

    .ubahpelanggan:hover {
        background-color: #fff2cc;
        color: black;
    }

    /* End Of Halaman Pelanggan */

    /* Halaman Jenis Cucian */
    .jeniscucian {
        background-color: white;
        margin-top: 75px;
        border-radius: 6px;
        padding: 20px;
    }

    .tambahjeniscucian {
        margin-top: 7px;
        background-color: #0b5394;
        color: white;
    }

    .tambahjeniscucian:hover {
        background-color: #fff2cc;
        color: black;
    }

    .ubahjeniscucian {
        background-color: #0b5394;
        color: white;
        width: 57px;
    }

    .ubahjeniscucian:hover {
        background-color: #fff2cc;
        color: black;
    }

    .hapusjeniscucian {
        background-color: #f44336;
        color: white;
    }

    .hapusjeniscucian:hover {
        color: black;
        background-color: #fff2cc;
    }

    /* End Of Halaman Jenis Cucian */

    /* Halaman Transaksi */

    .transaksi {
        background-color: white;
        margin-top: 75px;
        border-radius: 6px;
        padding: 20px;
    }

    .tambahtransaksi {
        margin-top: 7px;
        background-color: #0b5394;
        color: white;
    }

    .tambahtransaksi:hover {
        background-color: #fff2cc;
        color: black;
    }

    .cetaklaporan {
        margin-top: 7px;
        background-color: #0fa114;
        color: white;
    }

    .cetaklaporan:hover {
        background-color: #fff2cc;
        color: black;
    }

    .laporandd:hover {
        background-color: #fff2cc;
        color: black;
    }

    .statusselesai {
        margin-left: 20px;
        margin-right: 17px;
    }

    .ubahtransaksi {
        background-color: #0b5394;
        color: white;
        width: 57px;
    }

    .ubahtransaksi:hover {
        background-color: #fff2cc;
        color: black;
    }

    .hapustransaksi {
        background-color: #f44336;
        color: white;
    }

    .hapustransaksi:hover {
        color: black;
        background-color: #fff2cc;
    }

    /* End Of Halaman Transaksi */

    /* Halaman Detail Transaksi */

    .detailtransaksi {
        background-color: white;
        margin-top: 75px;
        border-radius: 6px;
        padding: 20px;
    }

    .tambahdetailtransaksi {
        background-color: #0fa114;
        color: white;
    }

    .tambahdetailtransaksi:hover {
        background-color: #fff2cc;
        color: black;
    }

    .hapusdetailtransaksi {
        background-color: #f44336;
        color: white;
    }

    .hapusdetailtransaksi:hover {
        color: black;
        background-color: #fff2cc;
    }

    .simperdetailtransaksi {
        background-color: #0fa114;
        color: white;
    }

    .simperdetailtransaksi:hover {
        background-color: #fff2cc;
        color: black;
    }

    /* End Of Halaman Detail Transaksi */
</style>